#
# helix configuration for local development
#
version: 1

definitions:
  defaults:
    - &defaultRepo "ssh://git@github.com/trieloff/helix-index-pipelines.git"

strains:
  - name: default
    code: ssh://git@github.com/trieloff/helix-index-pipelines.git#master
    content: ssh://git@github.com/trieloff/helix-index-pipelines.git#master
    static: ssh://git@github.com/trieloff/helix-index-pipelines.git/htdocs#master
    package: trieloff/43b1007f19768c846731be17f85e99b70b50ff76
