#
# helix configuration for local development
#
version: 1

definitions:
  defaults:
    - &defaultRepo "ssh://git@github.com/trieloff/helix-index-pipelines.git"

strains:
  - name: default
    code: ssh://git@github.com/trieloff/helix-index-pipelines.git#master
    content: ssh://git@github.com/trieloff/helix-index-pipelines.git#master
    static: ssh://git@github.com/trieloff/helix-index-pipelines.git/htdocs#master
    package: trieloff/github-com--trieloff--helix-index-pipelines--master-dirty

  - name: vision
    code: ssh://git@github.com/trieloff/helix-index-pipelines.git#azure-images
    content: ssh://git@github.com/trieloff/helix-index-pipelines.git#master
    static: ssh://git@github.com/trieloff/helix-index-pipelines.git/htdocs#master
    package: trieloff/github-com--trieloff--helix-index-pipelines--azure-images-dirty
