#
# helix configuration for local development
#
version: 1

definitions:
  defaults:
    - &defaultRepo "https://github.com/adobe/helix-index-pipelines.git#master"

strains:
  - name: default
    code: *defaultRepo
    content: *defaultRepo
    static: *defaultRepo
    package: helix-index-pipelines
